"""create salaries table

Revision ID: cac2b76a4eaf
Revises: 
Create Date: 2025-09-29 12:34:09.419706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac2b76a4eaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('server', sa.String(), nullable=False),
    sa.Column('online_hours', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Integer(), nullable=True),
    sa.Column('complaints', sa.Integer(), nullable=True),
    sa.Column('severe_complaints', sa.Integer(), nullable=True),
    sa.Column('attached_moderators', sa.Integer(), nullable=True),
    sa.Column('interviews', sa.Integer(), nullable=True),
    sa.Column('online_top', sa.Integer(), nullable=True),
    sa.Column('questions_top', sa.Integer(), nullable=True),
    sa.Column('gma_review', sa.Integer(), nullable=True),
    sa.Column('total_salary', sa.Float(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname', 'project', 'server', 'month', name='unique_salary')
    )
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_table('salaries')
    # ### end Alembic commands ###
